### ISSUE TITLE
How to https://maps.example.com

### ISSUE THREAD

**Issue by loyeyoung** [qwc-services/qwc-docker#75]
**Question**: How to set up qwc-docker to be addressable via https (on the default https port 443), using letsencrypt certbot?

**Expected result**: A user should type into his browser [https://maps.example.com](https://maps.example.com) and see the complete qwc-service web map.

**Background**:

I am trying to set up qwc-docker in a publicly facing production environment, such that [https://maps.example.com](https://maps.example.com) brings up the qwc2 map server and related services. Conceptually, it should be easy, and I have tried everything I can think of, but no luck.

**Tried so far**:

I was able to install qwc-docker on the server, which is solely dedicated to qwc-docker (i.e., not multi-tenant). The default configuration worked-- [http://maps.example.com:8088](http://maps.example.com:8088) brought up the server as expected. But the connection is insecure, and many client web browsers are configured for https only. (Also, the information that will be on the map is proprietary to our company, so security matters.)

I have installed HTTPS certificates on the host server via letsencrypt, and [https://maps.example.com](https://maps.example.com) brings up the default.html page on the server. 

However, I have struggled to implement https on the qwc-docker, spending two days banging my head against the wall. I have used [this how-to article](https://macdonaldchika.medium.com/how-to-install-tls-ssl-on-docker-nginx-container-with-lets-encrypt-5bd3bad1fd48) and read many others. (I have no particular attachment to any particular implementation.)

**Related issues**:

On [issue 64](https://github.com/qwc-services/qwc-docker/issues/64), [tpo](https://github.com/tpo) said: 
> In production you will maybe tweak a thing or another but that depends on what you need. F.ex.: HTTPS certificates via certbot

That's exactly what I'm trying to do.

**Server environment**: Debian Testing/trixie

**Comment by benoitblanc** [comment]
Hi,

You need to work on your nginx conf, located in qwc-docker repository ([`volumes/api-gateway/nginx-example.conf`](https://github.com/qwc-services/qwc-docker/blob/master/api-gateway/nginx-example.conf)). You need to copy this file and change your configuration on your needs. You can do what is explained in the article you linked and listen on port 443.

You also need to change exposed port of qwc-api-gateway service in docker-compose file to `443:443` for instance. https://github.com/qwc-services/qwc-docker/blob/master/docker-compose-example.yml#L288

**Comment by HusseinKabbout** [comment]
> I have installed HTTPS certificates on the host server via letsencrypt

Does this mean you already have a running web server on your host?

**Comment by loyeyoung** [comment]
@HusseinKabbout 

I am using nginx, per the default installation.

Received a **502 Bad Gateway** error.  The error log shows:
```
2024/01/22 11:00:24 [error] 40411#40411: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 192.##.##.140, server: maps.example.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8080/", host: "maps.example.com"
2024/01/22 11:00:57 [error] 40411#40411: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 192.##.##.140, server: maps.example.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8080/", host: "maps.example.com"
2024/01/22 11:00:59 [error] 40411#40411: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 192.##.##.140, server: maps.example.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8080/", host: "maps.example.com"
```

The 443 `server` block of the host's /etc/nginx/sites-enabled/qwc-docker.conf:
```
server {
	root /var/www/qwc-docker/;
	index index.php index.html index.htm index.nginx-debian.html;
    server_name maps.example.com; # managed by Certbot
	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
#		try_files $uri $uri/ =404;
# Per https://github.com/qwc-services/qwc-docker/issues/75#issuecomment-1904383255
            proxy_pass http://127.0.0.1:8080$uri$is_args$args;
	}
#    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/maps.example.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/maps.example.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
    add_header Strict-Transport-Security "max-age=31536000" always; # managed by Certbot
# Per https://github.com/qwc-services/qwc-docker/issues/75#issuecomment-1904383255
    proxy_set_header   Host              $http_host;
    proxy_set_header   X-Real-IP         $remote_addr;
    proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Proto $scheme;
}
```

The `qwc-api-gateway` portion of qwc-docker's docker-compose.yml:
```
  qwc-api-gateway:
    image: nginx:latest
    ports:
      - "127.0.0.1:8088:80"
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - qwc-postgis
      - qwc-config-service
      - qwc-qgis-server
      - qwc-ogc-service
      - qwc-map-viewer
      - qwc-auth-service
      - qwc-feature-info-service
      - qwc-legend-service
      - qwc-mapinfo-service
      - qwc-permalink-service
      - qwc-elevation-service
      - qwc-fulltext-search-service
      - qwc-data-service
      - qwc-admin-gui
      #- qwc-registration-gui
```

The ./api-gateway/nginx.conf file is the default.
